services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    image: ui:v1
    volumes:
      - ./:/usr/workspace
    environment:
      STAGE: ${STAGE}
      SUITE: ${SUITE:-regression}
      THREADS: ${THREADS:-5}
    command: /bin/sh -c "STAGE=$$STAGE pytest -sv -o log_cli=true -n=$$THREADS -m=$$MARKER --alluredir=allure-results" # Команда для выполнения в контейнере
    tty: true


  report:
    build:
      context: .
      dockerfile: Dockerfile
    image: ui:v1
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "ls -la && allure generate allure-results --clean -o allure-report"
    working_dir: /usr/workspace