services:
  tests:
    image: ui:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
      - ./allure-results:/usr/workspace/allure-results
    environment:
      STAGE: ${STAGE}
      SUITE: ${SUITE:-regression}
      THREADS: ${THREADS:-5}
    command: >
      /bin/sh -c "mkdir -p allure-results && STAGE=$$STAGE pytest -sv -o log_cli=true -n=$$THREADS -m \"$$SUITE\" --alluredir=allure-results"
    tty: true

  report:
    image: ui:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: >
      /bin/sh -c "ls -la allure-results && allure generate allure-results --clean -o allure-report"
    working_dir: /usr/workspace
