services:
  tests:
    image: ui:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
      - ./allure-results:/usr/workspace/allure-results
    environment:
      STAGE: ${STAGE}
      SUITE: ${SUITE:-regression}
      THREADS: ${THREADS:-5}
    command: >
      /bin/sh -c "rm -rf allure-results/* && mkdir -p allure-results && echo 'Running with SUITE: '$$SUITE && STAGE=$$STAGE pytest -sv -m \"$$SUITE\" --alluredir=allure-results && echo 'Tests completed, checking allure-results:' && ls -la allure-results/ && echo 'Contents of result files:' && find allure-results -name '*.json' -exec head -5 {} \\;"
    tty: true

  report:
    image: ui:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: >
      /bin/sh -c "echo 'Checking allure-results before generation:' && ls -la allure-results && echo 'JSON files content:' && find allure-results -name '*.json' -exec echo 'File: {}' \\; -exec cat {} \\; && allure generate allure-results --clean -o allure-report --verbose"
    working_dir: /usr/workspace
